language: csharp
solution: ./src/SetsCache.sln
mono: none
dotnet : 2.2
dist: xenial
script:
  - cd src
  - dotnet restore
  - dotnet test
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1